<?php

/**
 * Implements hook_filter_info().
 */
function kill_filter_info() {
  $filters = array();

  $filters['kill'] = array(
    'title' => t('Kill Non-Breaking Spaces'),
    'description' => t('Remove non-breaking spaces.'),
    'process callback' => '_kill',
    'tips callback' => '_kill_tips',
  );

  return $filters;
}

/**
 * Filter callbacks.
 */
function _kill($text, $filter) {
  return preg_replace('/&nbsp;/', ' ', $text);
}

/**
 * Filter tips.
 */
function _kill_tips($filter, $format, $long = FALSE) {
  if (!$long) {
    // This string will be shown in the content add/edit form.
    return t('Don\'t use non-breaking spaces.  Ever.');
  }
  else {
    // And this one on the "Filter Tips" page.
    return t('Non-breaking spaces are evil and will be eradicated.');
  }
}