<?php

require_once ("TcblFeed/FeedFactory.php");
require_once ("TcblFeed/FeedItem.php");
require_once ("TcblFeed/Plugins/FeedPlugin.php");
require_once ("TcblFeed/Plugins/FeedPluginInterface.php");

/**
 * Implements hook_block_info().
 */
function tcbl_feed_block_info() {
  return [
    'tcbl_feed' => [
      'info' => t("TCBL feed"),
      'cache' => DRUPAL_NO_CACHE,/*DRUPAL_CACHE_GLOBAL*/
    ],
  ];
}

/**
 * Implements hook_block_view().
 *
 * @param string
 * @returns array
 */
function tcbl_feed_block_view($delta = '') {
  $answer = [];

  if ($delta != 'tcbl_feed') {
    return $answer;
  }

  $answer['subject'] = t('TCBL Feeds');
  $answer['content'] = t('No feeds available.');


  //@todo: implement this with cron hook and remove it from here
  $generateOptions = [
    "feed_item_per_plugin" => 3,
  ];
  \TcblFeed\FeedFactory::generateFeeds($generateOptions);

  $getFeedOptions = [
    "filters" => [],
    "ordering" => "",
  ];
  $feeds = \TcblFeed\FeedFactory::getFeeds($getFeedOptions);


  if(count($feeds)) {
    //$answer['content'] = t('Number of feeds: ' . count($feeds));
    $answer['content'] = [];
    $answer['content']['feeds'] = [];

    /** @var \TcblFeed\FeedItem $feed */
    foreach($feeds as $feed)
    {
      $feedThemeItem = [
        '#theme' => 'tcbl_feed_item',
        '#feed_item' => $feed,
      ];
      array_push($answer['content']['feeds'], $feedThemeItem);
    }
  }

  return $answer;
}


/**
 * Implements hook_theme().
 */
function tcbl_feed_theme($existing, $type, $theme, $path) {
  return [
    'tcbl_feed_item' => [
      'template' => 'tcbl-feed-item',
      'variables' => [
        'feed_item' => NULL,
      ],
      /*'pattern' => 'tcbl-feed-item__',*/
    ],
  ];
}

