<?php

require('include/data.php');
require('include/query.php');

/**
 * Implementes hook_theme();
 */
function tcbl_labs_theme(){
  return array(
    'tcbl_labsmain' => array(
      // use a template and give the template's name.
      'template' => 'tcbl-labsmain',
      'variables' => array(
        'content' => NULL,
      ),
      'pattern' => 'tcbl-labsmain__',
    ),
  );
}

/**
 * Implements hook_preprocess_node();
 */
function tcbl_labs_preprocess_node(&$vars){
  $node = $vars['node'];
  if ($node->nid == 441 && $vars['view_mode'] == 'full'){
    _tcbl_labs_preprocess_mainlabs_node($vars);
  }
}

function _tcbl_labs_preprocess_mainlabs_node(&$vars){
  $node = $vars['node'];

  // Add parallax cover
  $vars['img_url'] = false;
  if (isset($node->field_image['und'][0]['uri'])){
    $uri = $node->field_image['und'][0]['uri'];
    $url_img = file_create_url($uri);  
    $vars['img_url'] = $url_img;

    $js_parallax = libraries_get_path('jquery.parallax') . '/jquery.parallax.min.js';
    drupal_add_js( $js_parallax , array('group' => JS_LIBRARY, 'weight' => 1));
  }

  // Add labs archive
  $vars['content']['archive'] = array(
    '#theme' => 'tcbl_labsmain',
    '#content' => _tcbl_labs_build_archive(),
  ); 
}

function template_preprocess_tcbl_labsmain(&$vars){
  // Add some js?
}

function _tcbl_labs_build_archive(){
  $build['nodes'] = _tcbl_labs_get_nodes();
  $data['list'] = _tcbl_labs_get_maps_data();

  $build['map'] = array(
    '#theme' => 'tcbl_map',
    '#data' => $data,
    '#multiple' => true,
  );

  return $build;
}


