<?php

require('include/data.php');
require('include/query.php');

function tcbl_labs_menu() {
  $items['labs-get-results'] = array(
    'title' => 'Labs query results',
    'page callback' => 'tcbl_labs_get_results_page',
    'access callback' => true,
  );
  $items['labs-get-data'] = array(
    'title' => 'Labs query results',
    'page callback' => 'tcbl_labs_get_data',
    'access callback' => true,
  );
  $items['labs-get-nids'] = array(
    'title' => 'Labs query nids',
    'page callback' => 'tcbl_labs_get_nids',
    'access callback' => true,
  );
  return $items;
}

/**
 * Result page for ajax load function
 */
function tcbl_labs_get_results_page() {
  $filters = $_GET;
  unset($filters['q']);

  $view_mode = 'teaser';
  if (isset($filters['view_mode'])){
    $view_mode = $filters['view_mode'];
    unset($filters['view_mode']);
  }

  $nids = _tcbl_labs_query_nids($filters);
  $build['nodes'] = _tcbl_labs_get_nodes($nids, $view_mode);
  return $build;
}

function tcbl_labs_get_data(){
  $filters = $_GET;
  unset($filters['q']);
  $nids = _tcbl_labs_query_nids($filters);
  $data = _tcbl_labs_get_maps_data($nids);
  return drupal_json_output($data);
}

function tcbl_labs_get_nids(){
  $filters = $_GET;
  unset($filters['q']);
  $nids = _tcbl_labs_query_nids($filters);
  return drupal_json_output($nids); 
}

/**
 * Implementes hook_theme();
 */
function tcbl_labs_theme(){
  return array(
    'tcbl_labsmain' => array(
      // use a template and give the template's name.
      'template' => 'tcbl-labsmain',
      'variables' => array(
        'content' => NULL,
        'data' => NULL,
      ),
      'pattern' => 'tcbl-labsmain__',
    ),
    'tcbl_labs_noresults' => array(
      // use a template and give the template's name.
      'template' => 'tcbl-labs-noresults',
      'variables' => array(
        'content' => NULL,
      ),
      'pattern' => 'tcbl-labs-noresults__',
    ),
  );
}

/**
 * Implements hook_preprocess_node();
 */
function tcbl_labs_preprocess_node(&$vars){
  $node = $vars['node'];
  if ($node->nid == 441 && $vars['view_mode'] == 'full'){
    _tcbl_labs_preprocess_mainlabs_node($vars);
  }
}

function _tcbl_labs_preprocess_mainlabs_node(&$vars){
  $node = $vars['node'];

  // Add parallax cover
  $vars['img_url'] = false;
  if (isset($node->field_image['und'][0]['uri'])){
    $uri = $node->field_image['und'][0]['uri'];
    $url_img = file_create_url($uri);  
    $vars['img_url'] = $url_img;

    $js_parallax = libraries_get_path('jquery.parallax') . '/jquery.parallax.min.js';
    drupal_add_js( $js_parallax , array('group' => JS_LIBRARY, 'weight' => 1));
  }

  $data['perPage'] = 8;

  // If an argument is present, cookie data need to by refreshed
  $data['withArgs'] = false;
  if (isset($_GET['country'])){
    $data['withArgs'] = true;
  }

  $data['scroll'] = false;
  if (isset($_GET['scroll'])){
    $data['scroll'] = true;
  }

  // Add labs archive
  $vars['content']['archive'] = array(
    '#theme' => 'tcbl_labsmain',
    '#content' => _tcbl_labs_build_archive($data),
    '#data' => $data,
  ); 
}

function template_preprocess_tcbl_labsmain(&$vars){
  $js = libraries_get_path('cookie') . '/js.cookie.min.js';
  drupal_add_js( $js , array('group' => JS_LIBRARY, 'weight' => 1));

  $js = libraries_get_path('jquery.simplepagination') . '/jquery.simplePagination.js';
  drupal_add_js( $js , array('group' => JS_LIBRARY, 'weight' => 1));

  $js = drupal_get_path('module', 'tcbl_labs') . '/js/tcbl-labs.js';
  drupal_add_js( $js , array('group' => JS_LIBRARY, 'weight' => 1));

  drupal_add_js(array(
    'tcbl_labs' => $vars['data'],
  ), array('type' => 'setting'));

}

function _tcbl_labs_build_archive(){
  $data['list'] = false;
  
  // All nids for filters
  $all_nids = _tcbl_labs_query_nids(array());
  $build['filters'] = _tcbl_labs_get_filters($all_nids);

  $build['map'] = array(
    '#theme' => 'tcbl_map',
    '#data' => $data,
    '#multiple' => true,
  );

  return $build;
}


