<?php

require('include/data.php');
require('include/query.php');

function tcbl_sruns_menu() {
  $items['shortruns'] = array(
    'title' => 'Short Runs',
    'page callback' => 'tcbl_sruns_page',
    'access callback' => true,
  );

  $items['shortruns/form'] = array(
    'title' => 'Short Runs - check-list',
    'page callback' => 'tcbl_sruns_filter_page',
    'access callback' => true,
  );

  $items['shortruns/search'] = array(
    'title' => 'Short Runs - search',
    'page callback' => 'tcbl_sruns_search_page',
    'access callback' => true,
  );

  return $items;
}

/**
 * Home page shortruns
 * @return [type] [description]
 */
function tcbl_sruns_page(){

  $js_parallax = libraries_get_path('jquery.parallax') . '/jquery.parallax.min.js';
  drupal_add_js( $js_parallax , array('group' => JS_LIBRARY, 'weight' => 1));

  $build = array(
    '#theme' => 'tcbl_sruns',
    '#content' => array(),
  );
  return $build;
}


function tcbl_sruns_filter_page(){

  $data['progress'] = _tcbl_sruns_get_progress_data();

  $build = array(
    '#theme' => 'tcbl_sruns_filter',
    '#content' => array(),
    '#data' => $data,
  );
  return $build;
}

function tcbl_sruns_search_page(){
  $build = array(
    '#theme' => 'tcbl_sruns_search',
    '#content' => array(),
  );
  return $build;
}

/**
 * Implementes hook_theme();
 */
function tcbl_sruns_theme(){
  return array(
    'tcbl_sruns' => array(
      'template' => 'tcbl-sruns',
      'variables' => array(
        'content' => NULL,
      ),
      'pattern' => 'tcbl-sruns__',
    ),
    'tcbl_sruns_filter' => array(
      'template' => 'tcbl-sruns-filter',
      'variables' => array(
        'content' => NULL,
        'data' => NULL,
      ),
      'pattern' => 'tcbl-sruns-filter__',
    ),
    'tcbl_sruns_search' => array(
      'template' => 'tcbl-sruns-search',
      'variables' => array(
        'content' => NULL,
      ),
      'pattern' => 'tcbl-sruns-search__',
    ),
  );
}

/**
 * Add usefull javascript libraries
 * @param  [type] &$vars [description]
 * @return [type]        [description]
 */
function template_preprocess_tcbl_sruns_filter(&$vars){
  $js = libraries_get_path('cookie') . '/js.cookie.min.js';
  drupal_add_js( $js , array('group' => JS_LIBRARY, 'weight' => 1));

  $js = libraries_get_path('underscore') . '/underscore-min.js';
  drupal_add_js( $js , array('group' => JS_LIBRARY, 'weight' => 1));

  $js = drupal_get_path('module', 'tcbl_sruns') . '/js/tcbl-sruns.js';
  drupal_add_js( $js , array('group' => JS_LIBRARY, 'weight' => 1));

  //if (user_access('access contextual links')){
  //  drupal_add_library('contextual', 'contextual-links');  
  //}

  //drupal_add_js(array(
  //  'tcbl_sruns' => $vars['data'],
  //), array('type' => 'setting'));
}

// ** ----- PREPROCES NODES----- **
// --------------------------------

/**
 * Implements hook_preprocess_node();
 */
function tcbl_sruns_preprocess_node(&$vars){
  $node = $vars['node'];
  switch ($node->type) {
    case 'resource':
      _tcbl_sruns_preprocess_resource($vars);
      break;

    case 'question':
      _tcbl_sruns_preprocess_question($vars);
      break;
    
    default:
      # code...
      break;
  }
}

function _tcbl_sruns_preprocess_resource(&$vars){
  $node = $vars['node'];
  if (isset($node->field_ref_res_type['und'][0]['tid'])){
    $tid = $node->field_ref_res_type['und'][0]['tid'];

    $vars['type_tid'] = $tid;
    $vars['content']['type_label']['#markup'] = 'Ask for help';

    switch ($tid) {
      case 245:
        $vars['content']['type_label']['#markup'] = 'Download resources';
        break;

      case 243:
        $vars['content']['type_label']['#markup'] = 'Read the article';
        break;
      
      case 246:
        $vars['content']['type_label']['#markup'] = 'Get IT solutions';
        break;

      case 247:
        $vars['content']['type_label']['#markup'] = 'Watch the video';
        break;

      default:
        # code...
        break;
    }
  }
}

function _tcbl_sruns_preprocess_question(&$vars){
  if ($vars['view_mode'] == 'full'){
    drupal_goto('shortruns/form');
  }
}
