<?php

require('include/data.php');
require('include/query.php');

function tcbl_comps_menu() {
  $items['comps-get-results'] = array(
    'title' => 'Labs query results',
    'page callback' => 'tcbl_comps_get_results_page',
    'access callback' => true,
  );
  $items['comps-get-data'] = array(
    'title' => 'Labs query results',
    'page callback' => 'tcbl_comps_get_data',
    'access callback' => true,
  );
  $items['comps-get-nids'] = array(
    'title' => 'Labs query nids',
    'page callback' => 'tcbl_comps_get_nids',
    'access callback' => true,
  );
  return $items;
}

/**
 * Result page for ajax load function
 */
function tcbl_comps_get_results_page() {
  $filters = $_GET;
  unset($filters['q']);

  $view_mode = 'teaser';
  if (isset($filters['view_mode'])){
    $view_mode = $filters['view_mode'];
    unset($filters['view_mode']);
  }

  $nids = _tcbl_comps_query_nids($filters);
  $build['nodes'] = _tcbl_comps_get_nodes($nids, $view_mode);
  return $build;
}

function tcbl_comps_get_data(){
  $filters = $_GET;
  unset($filters['q']);
  $nids = _tcbl_comps_query_nids($filters);
  $data = _tcbl_comps_get_maps_data($nids);
  return drupal_json_output($data);
}

function tcbl_comps_get_nids(){
  $filters = $_GET;
  unset($filters['q']);
  $nids = _tcbl_comps_query_nids($filters);
  return drupal_json_output($nids); 
}

/**
 * Implementes hook_theme();
 */
function tcbl_comps_theme(){
  return array(
    'tcbl_comps_main' => array(
      // use a template and give the template's name.
      'template' => 'tcbl-comps-main',
      'variables' => array(
        'content' => NULL,
        'data' => NULL,
        'aid' => NULL,
      ),
      'pattern' => 'tcbl-comps-main__',
    ),
    'tcbl_comps_noresults' => array(
      // use a template and give the template's name.
      'template' => 'tcbl-comps-noresults',
      'variables' => array(
        'content' => NULL,
      ),
      'pattern' => 'tcbl-comps-noresults__',
    ),
  );
}

/**
 * Add usefull javascript libraries
 * @param  [type] &$vars [description]
 * @return [type]        [description]
 */
function template_preprocess_tcbl_comps_main(&$vars){
  $js = libraries_get_path('cookie') . '/js.cookie.min.js';
  drupal_add_js( $js , array('group' => JS_LIBRARY, 'weight' => 1));

  $js = libraries_get_path('jquery.simplepagination') . '/jquery.simplePagination.js';
  drupal_add_js( $js , array('group' => JS_LIBRARY, 'weight' => 1));

  $js = drupal_get_path('module', 'tcbl_comps') . '/js/tcbl-comps.js';
  drupal_add_js( $js , array('group' => JS_LIBRARY, 'weight' => 1));

  drupal_add_js(array(
    'tcbl_comps' => $vars['data'],
  ), array('type' => 'setting'));
}

// ** ----- PREPROCES SNODES----- **
// ---------------------------------

/**
 * Implements hook_preprocess_node();
 */
function tcbl_comps_preprocess_node(&$vars){
  $node = $vars['node'];

  if ($node->nid == 441 && $vars['view_mode'] == 'full'){
    _tcbl_comps_pre_labs_node($vars);
  }

  if ($node->nid == 486 && $vars['view_mode'] == 'full'){
    _tcbl_comps_pre_directory_node($vars);
  }
}

/**
 * Preprocess Labs Page to add Labs archive
 */
function _tcbl_comps_pre_labs_node(&$vars){
  $node = $vars['node'];

  // Add parallax cover
  $vars['img_url'] = false;
  if (isset($node->field_image['und'][0]['uri'])){
    $uri = $node->field_image['und'][0]['uri'];
    $url_img = file_create_url($uri);  
    $vars['img_url'] = $url_img;

    $js_parallax = libraries_get_path('jquery.parallax') . '/jquery.parallax.min.js';
    drupal_add_js( $js_parallax , array('group' => JS_LIBRARY, 'weight' => 1));
  }

  $data['perPage'] = 8;

  // If an argument is present, cookie data need to by refreshed
  $data['withArgs'] = false;
  if (isset($_GET['country'])){
    $data['withArgs'] = true;
  }

  $data['scroll'] = false;
  if (isset($_GET['scroll'])){
    $data['scroll'] = true;
  }

  // Default filters
  $data['filters'] = array(
    'memb' => 28, // Only labs
  );

  // Archive id (for cookies)
  $data['id'] = 'labs';

  // Add comps archive
  $vars['content']['archive'] = array(
    '#theme' => 'tcbl_comps_main',
    '#content' => _tcbl_comps_build_archive($data['filters']),
    '#data' => $data,
    '#aid' => $data['id'],
  ); 
}

/**
 * Preprocess Directory Page to add Directory archive
 */
function _tcbl_comps_pre_directory_node(&$vars){
  $node = $vars['node'];

  $data['perPage'] = 8;

  // If an argument is present, cookie data need to by refreshed
  $data['withArgs'] = false;
  if (isset($_GET['country'])){
    $data['withArgs'] = true;
  }

  $data['scroll'] = false;
  if (isset($_GET['scroll'])){
    $data['scroll'] = true;
  }

  // Default filters
  $data['filters'] = array(
    'memb' => 'all',
  );

  // Archive id (for cookies)
  $data['id'] = 'directory';

  // Add comps archive
  $vars['content']['archive'] = array(
    '#theme' => 'tcbl_comps_main',
    '#content' => _tcbl_comps_build_archive($data['filters']),
    '#data' => $data,
    '#aid' => $data['id'],
  ); 
}

/**
 * Build comps archive with map and list
 */
function _tcbl_comps_build_archive($filters){
  $data['list'] = false;
  
  // All nids for filters
  $all_nids = _tcbl_comps_query_nids($filters);

  // Filters
  $build['filters'] = _tcbl_comps_get_filters($all_nids);

  $build['map'] = array(
    '#theme' => 'tcbl_map',
    '#data' => $data,
    '#multiple' => true,
  );

  return $build;
}


