<?php

/**
 * @param array $vars
 */
function tcbl_frontpage_preprocess_page(&$vars) {
  if (!isset($vars['is_front']) || $vars['is_front'] != TRUE) {
    return;
  }

  $content = array();

  $content['news']['#markup'] = views_embed_view('hp_news', 'default');
  $content['events']['#markup'] = views_embed_view('hp_events', 'default');
  $content['forum']['#markup'] = views_embed_view('hp_forum', 'default');

  // Business Pilots
  $bpilots_node = node_load(310);
  $bpilots_node_view = node_view($bpilots_node, 'teaser');
  $content['bpilots'] = $bpilots_node_view['field_short'];
  $uri = $bpilots_node->field_image['und'][0]['uri'];
  $url_img = file_create_url($uri);
  $content['bpilots_img_path']['#markup'] = $url_img;
  $opt = array(
    'attributes' => array(
      'class' => array('btn', 'btn-info', 'bnt-lg', 'margin-t-1'),
    ),
  );
  $content['bpilots_more'] = array(
    '#markup' => l('Explore Business Cases', 'node/310', $opt),
  );

  $js_parallax = libraries_get_path('jquery.parallax') . '/jquery.parallax.min.js';
  drupal_add_js( $js_parallax , array('group' => JS_LIBRARY, 'weight' => 1));

  $show_sign_up = !user_is_logged_in();
  $vars['page']['content']['front'] = [
    '#theme' => 'tcblfront',
    '#content' => $content,
    '#tcbl_feeds' => _tcbl_frontpage_get_tcbl_feeds(),
    '#show_sign_up' => $show_sign_up,
  ];
}

/**
 * @return array
 */
function _tcbl_frontpage_get_tcbl_feeds() {

  $generate_feed_options = [
    /*
    "feed_item_per_plugin" => [
      "default" => 3,
      "tcbl_zine" => 4,
      "facebook" => 2,
      "instagram" => 2,
      "twitter" => 2,
    ],*/
    "default" => [
      "max_items" => 3
    ],
    "plugin" => [
      "tcbl_zine" => [
        "max_items" => 4
      ],
      "tcbl_labs" => [
        "max_items" => 3
      ],
      "facebook" => [
        "max_items" => 2,
        'app_id' => '301393660390585',
        'app_secret' => 'fa161c64d4663bf34c562c007a02dc59',
        'default_graph_version' => 'v2.12',
      ],
      "instagram" => [
        "max_items" => 2
      ],
      "twitter" => [
        "max_items" => 2,
        "consumer_key"            => "05rhm0AJq1Wcl8VdVR1EKb1qY",
        "consumer_secret"         => "ozj7VwhS2GO3anJTpS82OWUtrEEzx7uwSKCh7bWEhIoVA3swl3",
        "access_token"            => "776749216442056704-9hZR2zniP7UTabNDtOFdFowoPDqhMpj",
        "access_token_secret"     => "mqx0lSHqvYNKErjd1cXRSzl8M9XJ05Jz57bBEWCZAEhQE",
      ],
    ]
  ];
  tcbl_feed_generate_feeds($generate_feed_options);


  //------------------------------------------ZINE
  $zine_get_feed_opts = [
    "filters" => [
      "source" => ["tcbl_zine"]
    ],
    "ordering" => [
      "property" => "creation_date",
      "order" => "DESC"
    ]
  ];

  //------------------------------------------LABS
  $labs_get_feed_opts = [
    "filters" => [
      "source" => ["tcbl_labs"]
    ],
    "ordering" => [
      "property" => "creation_date",
      "order" => "DESC"
    ]
  ];

  //------------------------------------------SOCIAL
  $social_get_feed_opts = [
    "filters" => [
      "source" => ["facebook", "twitter", "instagram"]
    ],
    "ordering" => [
      "property" => "creation_date",
      "order" => "DESC"
    ]
  ];

  return [
    'zine' => tcbl_feed_get_renderable_feeds($zine_get_feed_opts),
    'labs' => tcbl_feed_get_renderable_feeds($labs_get_feed_opts),
    'social' => tcbl_feed_get_renderable_feeds($social_get_feed_opts)
  ];
}

/**
 * Implements hook_theme().
 */
function tcbl_frontpage_theme() {
  return array(
    'tcblfront' => array(
      // use a template and give the template's name.
      'template' => 'tcblfront',
      'variables' => array(
        'content' => NULL,
        'tcbl_feeds' => NULL,
        'show_sign_up' => FALSE,
      ),
      'pattern' => 'tcblfront__',
    )
  );
}