<?php

/**
 * @param array $vars
 */
function tcbl_frontpage_preprocess_page(&$vars) {
  if (!isset($vars['is_front']) || $vars['is_front'] != TRUE) {
    return;
  }

  $content = array();

  // News
  $content['news']['#markup'] = views_embed_view('hp_news', 'default');

  // Se ci sono eventi nel futuro (rispetto ad oggi)
  $view = views_get_view_result('hp_events', 'default');
  $result = count($view);
  if ($result) {
    // Eventi del futuro
    $content['events']['#markup'] = views_embed_view('hp_events', 'default');  
  } else {
    // Eventi del passato
    $content['events']['#markup'] = views_embed_view('hp_events_past', 'default'); 
  }

  // Forum
  // $content['forum']['#markup'] = views_embed_view('hp_forum', 'default');

  // Business Pilots
  $bpilots_node = node_load(310);
  $bpilots_node_view = node_view($bpilots_node, 'teaser');
  $content['bpilots'] = $bpilots_node_view['field_short'];
  $uri = $bpilots_node->field_image['und'][0]['uri'];
  $url_img = file_create_url($uri);
  $content['bpilots_img_path']['#markup'] = $url_img;
  $opt = array(
    'attributes' => array(
      'class' => array('btn', 'btn-info', 'bnt-lg', 'margin-t-1'),
    ),
  );
  $content['bpilots_more'] = array(
    '#markup' => l('Explore Business Pilots', 'node/310', $opt),
  );

  // Banner
  $set = _tcbl_get_tcbl_settings();
  if (isset($set->field_ref_banner_home['und'][0]['target_id'])){
    $banner = node_load($set->field_ref_banner_home['und'][0]['target_id']);
    if ($banner){
      $content['banner'] = node_view($banner, 'child');  
    }
  }

  // Libraries
  $js_parallax = libraries_get_path('jquery.parallax') . '/jquery.parallax.min.js';
  drupal_add_js( $js_parallax , array('group' => JS_LIBRARY, 'weight' => 1));
  $js_sameh = libraries_get_path('jquery.sameh') . '/jquery.sameh.js';
  drupal_add_js( $js_sameh , array('group' => JS_LIBRARY, 'weight' => 1));
  add_same_h_by_selector('.wrapper-zine-sameh');

  $show_sign_up = !user_is_logged_in();
  $vars['page']['content']['front'] = [
    '#theme' => 'tcblfront',
    '#content' => $content,
    '#tcbl_feeds' => _tcbl_frontpage_get_tcbl_feeds(),
    '#show_sign_up' => $show_sign_up,
  ];
}

/**
 * @return array
 */
function _tcbl_frontpage_get_tcbl_feeds() {
  //------------------------------------------ZINE
  $zine_get_feed_opts = [
    "filters" => [
      "source" => ["tcbl_zine"]
    ],
    "ordering" => [
      "property" => "creation_date",
      "order" => "DESC"
    ]
  ];

  //------------------------------------------LABS
  $labs_get_feed_opts = [
    "filters" => [
      "source" => ["tcbl_labs"]
    ],
    "ordering" => [
      "property" => "creation_date",
      "order" => "DESC"
    ]
  ];

  //------------------------------------------SOCIAL
  $social_get_feed_opts = [
    "filters" => [
      "source" => ["facebook", "twitter", "instagram"]
    ],
    "ordering" => [
      "property" => "creation_date",
      "order" => "DESC"
    ],
    "max_items" => 4,
  ];

  return [
    'zine' => tcbl_feed_get_renderable_feeds($zine_get_feed_opts),
    'labs' => tcbl_feed_get_renderable_feeds($labs_get_feed_opts),
    'social' => tcbl_feed_get_renderable_feeds($social_get_feed_opts)
  ];
}

/**
 * Implements hook_theme().
 */
function tcbl_frontpage_theme() {
  return array(
    'tcblfront' => array(
      // use a template and give the template's name.
      'template' => 'tcblfront',
      'variables' => array(
        'content' => NULL,
        'tcbl_feeds' => NULL,
        'show_sign_up' => FALSE,
      ),
      'pattern' => 'tcblfront__',
    )
  );
}