<?php

function tcbl_map_menu(){
  $items['tcbl-map/save/%/%/%'] = array(
    'title' => 'Tcbl Map Save Page',
    'description' => 'Tcbl Map Save Page',
    'page callback' => '_tcbl_map_save_page',
    'page arguments' => array(2,3,4),
    'access callback' => true,
  );
  return $items;
}

function tcbl_map_library() {

  // Bisogna riscrivere con questa guida
  // https://docs.mapbox.com/help/tutorials/use-mapbox-js-as-fallback/

  // New library
  $libraries['leafletjs'] = [
    'title' => 'Leaflet JS',
    'website' => 'https://leafletjs.com/',
    'version' => '1.7.1',
    'js' => [
      'https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js' => [
        'type' => 'external',
        'weight' => 1,
      ],
      'https://unpkg.com/leaflet@1.7.1/dist/leaflet.js' => array(
        'type' => 'external',
        'weight' => 4,
      ),
      drupal_get_path('module', 'tcbl_map') . '/js/tcbl-map.js' => array(
        'type' => 'file',
        'weight' => 5,
      ),
    ],
    'css' => [
      'https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css' => [
        'type' => 'external',
        'weight' => 1,
      ],
      'https://unpkg.com/leaflet@1.7.1/dist/leaflet.css' => array(
        'type' => 'external',
        'weight' => 1,
      ),
    ],
  ];

  $libraries['leafletjsmulti'] = [
    'title' => 'Leaflet JS',
    'website' => 'https://leafletjs.com/',
    'version' => '1.7.1',
    'js' => [
      'https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js' => [
        'type' => 'external',
        'weight' => 1,
      ],
      'https://unpkg.com/leaflet@1.7.1/dist/leaflet.js' => array(
        'type' => 'external',
        'weight' => 4,
      ),
      drupal_get_path('module', 'tcbl_map') . '/js/tcbl-map-multiple.js' => array(
        'type' => 'file',
        'weight' => 5,
      ),
    ],
    'css' => [
      'https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css' => [
        'type' => 'external',
        'weight' => 1,
      ],
      'https://unpkg.com/leaflet@1.7.1/dist/leaflet.css' => array(
        'type' => 'external',
        'weight' => 1,
      ),
    ],
  ];

  return $libraries;
}

/**
 * Implementes hook_theme();
 */
function tcbl_map_theme(){
  return array(
    'tcbl_map' => array(
      // use a template and give the template's name.
      'template' => 'tcbl-map',
      'variables' => array(
        'data' => NULL,
        'multiple' => false,
      ),
      'pattern' => 'tcbl-map__',
    ),
  );
}

function template_preprocess_tcbl_map(&$vars){

  $js = libraries_get_path('underscore') . '/underscore-min.js';
  drupal_add_js( $js , array('group' => JS_LIBRARY, 'weight' => 1));

  // Aggiungo le librerie necessarie a Leaflet Js
  if ($vars['multiple']){
    drupal_add_library('tcbl_map', 'leafletjsmulti');
  } else {
    drupal_add_library('tcbl_map', 'leafletjs');  
  }

  if (!isset($vars['data']['mid'])){
    $vars['data']['mid'] = 'map';  
  }

  drupal_add_js(array(
    'tcbl_map' => $vars['data'],
  ), array('type' => 'setting'));

}

function _tcbl_map_save_page($nid, $lat, $lon){
  if ($nid){
    $company = node_load($nid);
    if ($company->type == 'company'){
      $data['coord'] = 'ok';
      $company->field_geolocation['und'][0]['first'] = $lat;
      $company->field_geolocation['und'][0]['second'] = $lon;
      $data['result'] = 'saved';
      node_save($company);
    }
  } else {
    $data['coord'] = 'false';
    $data['result'] = 'nothing to do';
  }
  drupal_json_output($data);
}


